//
//  DeveloperSettingsView.swift
//  App (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/app#developer-view
//
//  Use this developer settings view to adjust settings,
//  enable/disable features, etc. on the fly to help you with the development process.
//
//  This View is only shown in 'Debug / Development' Release Mode
//  DEBUG = Not App Store or TestFlight build
//

import SharedKit
import SwiftUI

struct DeveloperSettingsView: View {

	/// Will persist the setting on whether to always require biometric auth or just hide the view in the app switcher.
	///
	/// Used as a demo for .sensitiveView()
	@AppStorage("protectDeveloperViewWithBiometrics") private var protectDeveloperViewWithBiometrics: Bool = false

	@State private var showSheetThatRequiredNetworkAccess = false

	@State private var showOnboarding = false
	@State private var showFeatureSheet = false

	var body: some View {
		NavigationStack {
			#if DEBUG
				List {
					Section {
						Button("Show Onboarding") {
							showOnboarding = true
						}

						Button("Show Feature Sheet") {
							showFeatureSheet = true
						}

						Button("Reset UserDefaults") {
							UserDefaults.standard.clear()
						}

						Button("Send InApp Notification") {
							showInAppNotification(
								.info,
								content: InAppNotificationContent(
									title: "Info Notification",
									message: "This is a normal Notification"),
								size: .normal
							) {
								print("hello")
							}
						}

						Button("Send Compact InApp Notification") {
							showInAppNotification(
								content: .init(
									title: "Custom Notification",
									message: "Compact Notification"),
								style: .init(
									sfSymbol: "star.fill", symbolColor: .indigo,
									size: .compact)
							)
						}

						Button("View that Requires Network Access") {
							showSheetThatRequiredNetworkAccess = true
						}

						Toggle(
							"Protect this View with Biometrics",
							isOn: $protectDeveloperViewWithBiometrics)
					}

					Section(header: Text("Ask User For...")) {

						// just examples on how to use `askUserFor` actions.
						Button("Will Ask for Review on 10th tap") {
							askUserFor(.appRating) {
								print(
									"Won't show rating sheet. Already prompted or not performing for the 10th time."
								)
							} onDismiss: {
								print("User Dimissing Rating Sheet.")
							}
						}

						Button("Ask for Photo Library Permission") {
							askUserFor(.photosAccess) {
								showInAppNotification(
									.success,
									content: .init(
										title: "Got Photos Access!", message: "Nice."))
							} onDismiss: {
								showInAppNotification(
									.warning,
									content: .init(
										title: "Dismissed :(",
										message: "User Declined Permission."))
							}
						}

						Button("Ask for Camera Permission") {
							askUserFor(.cameraAccess)
						}

						Button("Ask for Microphone Permission") {
							askUserFor(.microphoneAccess)
						}

						Button("Ask for Location Access") {
							askUserFor(.locationAccess)
						}

						Button("Ask for Contacts Access") {
							askUserFor(.contactsAccess)
						}

						Button("Ask for Calendar Access") {
							askUserFor(.calendarAccess)
						}

						Button("Ask for Reminders Access") {
							askUserFor(.remindersAccess)
						}
					}

				}
				.navigationTitle("Developer Settings")
				.sheet(isPresented: $showFeatureSheet) {
					ShowFeatureSheetOnNewAppVersionModifier.WhatsNewView {
						showFeatureSheet = false
					}
				}
				.sheet(isPresented: $showOnboarding) {
					KoltOnboardingView(iCloudEnabled: false, setICloudSync: { _ in }) {
						showOnboarding = false
					}
				}

			#endif
		}
		.sensitiveView(protectWithBiometrics: protectDeveloperViewWithBiometrics)
		.sheet(isPresented: $showSheetThatRequiredNetworkAccess) {
			Text("Congrats, you have Internet Access!")
				.requireNetwork()
		}
	}
}

#Preview {
	DeveloperSettingsView()
}
